package com.example.service;

import java.io.OutputStream;

import com.example.model.BusPass;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.BorderRadius;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

public class BusPassPdfService {

    
    public void generateBusPassPdf(BusPass pass, OutputStream out) {

        try {
            PdfWriter writer = new PdfWriter(out);
            PdfDocument pdfDoc = new PdfDocument(writer);
            Document document = new Document(pdfDoc);

            PdfFont headerFont = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);
            PdfFont valueFont = PdfFontFactory.createFont(StandardFonts.HELVETICA);

            // ✅ Title
            Paragraph title = new Paragraph("Bus Pass")
                    .setFont(headerFont)
                    .setFontSize(24)
                    .setFontColor(new DeviceRgb(0, 102, 204))
                    .setTextAlignment(TextAlignment.CENTER)
                    .setMarginBottom(20);

            document.add(title);

            // ✅ Table
            Table table = new Table(UnitValue.createPercentArray(new float[]{2, 4}))
                    .useAllAvailableWidth()
                    .setHorizontalAlignment(HorizontalAlignment.CENTER);

            addRow(table, "Pass ID", String.valueOf(pass.getId()), headerFont, valueFont);
            addRow(table, "Name", pass.getName(), headerFont, valueFont);
            addRow(table, "Email", pass.getEmail(), headerFont, valueFont);
            addRow(table, "Pass Type", pass.getPassType(), headerFont, valueFont);
            addRow(table, "Start Date", pass.getStartDate(), headerFont, valueFont);
            addRow(table, "End Date", pass.getEndDate(), headerFont, valueFont);

            document.add(table);

            // ✅ Footer
            Paragraph footer = new Paragraph("\nGenerated by Bus Pass Registration System")
                    .setFontSize(10)
                    .setFontColor(new DeviceRgb(120, 120, 120))
                    .setTextAlignment(TextAlignment.CENTER);

            document.add(footer);

            document.close();

        } catch (Exception e) {
            throw new RuntimeException("PDF generation failed", e);
        }
    }

    private void addRow(Table table, String key, String value, PdfFont headerFont, PdfFont valueFont) {

        Cell keyCell = new Cell()
                .add(new Paragraph(key).setFont(headerFont).setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(new DeviceRgb(255, 87, 34))  // orange
                .setPadding(10)
                .setBorder(new SolidBorder(ColorConstants.WHITE, 1))
                .setBorderRadius(new BorderRadius(6));

        Cell valueCell = new Cell()
                .add(new Paragraph(value != null ? value : "").setFont(valueFont))
                .setBackgroundColor(new DeviceRgb(255, 236, 179)) // light yellow
                .setPadding(10)
                .setBorder(new SolidBorder(ColorConstants.WHITE, 1))
                .setBorderRadius(new BorderRadius(6));

        table.addCell(keyCell);
        table.addCell(valueCell);
    }
}
